var validate = function(input) {
    var strip = function(text) {
        return text.toLowerCase().replace(/[\s.,\/#!$%\^&\*;:{}=\-_'"`~()]/g, "");
    }
    if (strip(input).length > 0)  return true;
    return false;
}

var task = {
    "name": "Information Finding",
    "instruction": [
        "In this task, you will find the <b>Middle Name</b> of a famous person by searching with provided information using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>.",
    ],
    "question_number": 5,
    "time_limit": "20 minutes",
    "questions": [
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Brian Smith</b> (profession: <b>Ice Hockey</b>, year: <b>1955<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Christopher Porter</b> (profession: <b>Football Goalkeeper</b>, year: <b>2009<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Gary Smith</b> (profession: <b>English Footballer</b>, year: <b>2011<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>John Palmer</b> (profession: <b>English Politician</b>, year: <b>1868<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Michael Murphy</b> (profession: <b>Irish Politician</b>, year: <b>1970<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Alberto Fontana</b> (profession: <b>Football Goalkeeper</b>, year: <b>2011<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Charles Davis</b> (profession: <b>US Army</b>, year: <b>1943<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>George Russell</b> (profession: <b>Irish Painter</b>, year: <b>1918<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Johann Bach</b> (profession: <b>Composer</b>, year: <b>1671<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Michael Murphy</b> (profession: <b>American Politician</b>, year: <b>1901<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Johann Bach</b> (profession: <b>Composer</b>, year: <b>1703<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Kevin Johnson</b> (profession: <b>American Football</b>, year: <b>1995<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Brian Smith</b> (profession: <b>American Actor</b>, year: <b>2004<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>John Palmer</b> (profession: <b>US Senator</b>, year: <b>1894<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>William Wilson</b> (profession: <b>Alberta Politician</b>, year: <b>1918<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Brian Smith</b> (profession: <b>Academic Researcher, Strategic Management</b>, year: <b>1989<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Brian Smith</b> (profession: <b>American Football Linebacker</b>, year: <b>1989<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Brian Smith</b> (profession: <b>Ice Hockey</b>, year: <b>1972<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Michael Murphy</b> (profession: <b>Folk Musician</b>, year: <b>1975<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Christopher Davis</b> (profession: <b>American Major League Baseball</b>, year: <b>2009<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Gary Smith</b> (profession: <b>English Footballer</b>, year: <b>1995<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Michael Murphy</b> (profession: <b>Political Consultant</b>, year: <b>2005<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Mark Johnson</b> (profession: <b>Americal Major League Baseball</b>, year: <b>2008<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Richard Harris</b> (profession: <b>American Football</b>, year: <b>1970<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Charles Davis</b> (profession: <b>American Football</b>, year: <b>1987<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Johann Bach</b> (profession: <b>Composer</b>, year: <b>1760<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Charles Davis</b> (profession: <b>American Football</b>, year: <b>1976<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Charles Davis</b> (profession: <b>American Football</b>, year: <b>2011<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Bradley Smith</b> (profession: <b>Australian Footballer</b>, year: <b>1999<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Roger Taylor</b> (profession: <b>Drummer</b>, year: <b>1968<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Brandon Miller</b> (profession: <b>American Football</b>, year: <b>2008<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>John Lucas</b> (profession: <b>Basketball Player</b>, year: <b>1976<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Bradley Smith</b> (profession: <b>American Football</b>, year: <b>2013<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Brian Smith</b> (profession: <b>Scholar in Cognitive Science</b>, year: <b>1982<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Mark Smith</b> (profession: <b>American Author, Comic Books</b>, year: <b>2009<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>William Wilson</b> (profession: <b>Pennsylvania Politician</b>, year: <b>1914<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Christopher Evans</b> (profession: <b>Politician</b>, year: <b>1993<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Charles Davis</b> (profession: <b>Basketball</b>, year: <b>2014<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Charles Davis</b> (profession: <b>US Navy</b>, year: <b>1830<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>William Wilson</b> (profession: <b>Oregon Politician</b>, year: <b>1845<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>George Russell</b> (profession: <b>New Zealand Politician</b>, year: <b>1918<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Gary Smith</b> (profession: <b>English Footballer</b>, year: <b>1975<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Jim Bedard</b> (profession: <b>Ice Hockey</b>, year: <b>1976<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Michael Murphy</b> (profession: <b>Ice Hockey</b>, year: <b>1971<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Franklin Roosevelt</b> (profession: <b>President</b>, year: <b>1935<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Stuart Beavon</b> (profession: <b>Footballer</b>, year: <b>2012<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Bradley Smith</b> (profession: <b>Australian Footballer</b>, year: <b>2014<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>George Bush</b> (profession: <b>President</b>, year: <b>2008<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>Joseph Kennedy</b> (profession: <b>Businessman, Politician</b>, year: <b>1938<b/>)"]},
        {"question": ["Please find the <b>Middle Name</b> of this person using <a href=\"http://en.wikipedia.org/\" target=\"_blank\">Wikipedia</a> or <a href=\"http://www.google.com\" target=\"_blank\">Google</a>:", "<b>John Adams</b> (profession: <b>President</b>, year: <b>1826<b/>)"]}
    ]
}
